version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/src
    environment:
      DEPLOYMENT_GITHUB_SSH_URL: git@github.com:2shortplanks/optomized.systems-deploy.git
    steps:
      # checkout
      - checkout
      - run: git submodule sync && git submodule update --init

      # clone the deployment repo
      - run:
          name: Clone the deployment repository
          command: |
            ssh-add -D
            ssh-add <(echo $GITHUB_SSH_KEY | base64 -d)
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
            git clone -–depth 1 $DEPLOYMENT_GITHUB_SSH_URL ~/output

      - run:
          name: Build with hugo
          command: HUGO_ENV=production hugo -v -d ~/output

      - run:
          name: commit the changes to the deployment repo
          command: |
            export COMMIT_SHA=$(git rev-parse HEAD)
            cd ~/output
            git add .
            git config --global user.email "bottymcbotface@twoshortplanks.com"
            git config --global user.name "Deploy Bot"
            git commit -m "Automated update for commit ${COMMIT_SHA}"

      - deploy:
          name: deploy to github
          command: cd ~/output && git push
