version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/build
    steps:
      # clone the deployment repo
      - run:
          name: clone the deployment repo
          command: |
            mkdir ~/.ssh
            chmod 700 ~/.ssh
            echo $GITHUB_SSH_KEY | base64 -d > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' > ~/.ssh/known_hosts
            git clone git@github.com:2shortplanks/optomized.systems-deploy.git ~/output

      - checkout

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      - run:
          name: build with hugo
          command: HUGO_ENV=production hugo -v -d ~/output

      - run:
          name: commit the changes to the deployment repo
          command: |
            export COMMIT_SHA=$(git rev-parse HEAD)
            cd ~/output
            git add .
            git config --global user.email "bottymcbotface@twoshortplanks.com"
            git config --global user.name "Mark Fowler's Deploy Bot"
            git commit -m "Automated update for commit ${COMMIT_SHA}"

      - deploy:
          name: deploy to github
          command: cd ~/output && git push
